baseURL = "/"
languageCode = "ro-ro"
summaryLength = "10"
theme = "kross-hugo"
title = "Good PC - Service IT, Reparatii Calculatoare - Laptopuri"
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 4
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5
[params]
address = "Nr. 228, Bl.4, Calea Griviței, București 010763"
author = "Bogdan Bunea"
copyright = " &copy; [goodpc.ro](https://goodpc.ro) 2015 - 2020 "
description = "Reparăm orice calculator, laptop în 24h. Oferim garanție și prețuri atractive."
email = "goodpcro@gmail.com"
google_analitycs_id = "Your ID"
home = "Home"
logo = "/images/logo.svg"
phone = "+4 0786 465 756"
theme_color = "#00DDFF"
[params.contact]
enable = true
form_action = "#"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = "/images/168.gif"
[[params.social]]
URL = "https://www.facebook.com/goodpcro/"
icon = "ti-facebook"
[[params.social]]
URL = "#"
icon = "ti-instagram"
[[params.social]]
URL = "#"
icon = "ti-dribbble"
[[params.social]]
URL = "#"
icon = "ti-twitter-alt"
